profiles/urls.py
from . import views
from django.urls import path


# name of url.py
name = 'profiles_urls'


# Profile URL patterns
urlpatterns = [
    path('profiles/profile/', views.profile, name='profile'),
    path('profiles/fav/<int:id>/', views.favourite_add, name='favourite_add'),
    path('profiles/favourites/', views.favourites, name='favourites'),
]

seasonality/urls.py
from django.contrib import admin
from django.urls import path, include


# Main Url Patterns, pulls from both apps
urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('recipebook.urls'), name='recipebook_urls'),
    path('profile/', include('profiles.urls'), name='profiles_urls'),
    path('accounts/', include('allauth.urls')),
]

recipebook/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.db.models import Avg


# Status for wether recipe is published
STATUS = ((0, "Draft"), (1, "Published"))


# Season Model - category
class Season(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Diet Model - category
class Diet(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Recipe Model - deals with all of the recipe metadata
class Recipe(models.Model):

    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter()

    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipes"
    )
    diet = models.ForeignKey(
        Diet, on_delete=models.CASCADE, default=True, null=False)
    season = models.ForeignKey(
        Season, on_delete=models.CASCADE, default=True, null=False)
    featured_image = CloudinaryField('image', default='placeholder')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    ingredients = models.TextField(default='placeholder')
    calories = models.IntegerField(default=0)
    fat = models.IntegerField(default=0)
    protein = models.IntegerField(default=0)
    carbs = models.IntegerField(default=0)
    servs = models.IntegerField(default=0)
    favourites = models.ManyToManyField(
        User, related_name='favourite', default=None, blank=True)
    objects = models.Manager()
    newmanager = NewManager()

    class Meta:
        ordering = ["-created_on"]

    def average_rating(self) -> float:
        return Rating.objects.filter(
            recipe=self).aggregate(Avg("rating"))["rating__avg"] or 0

    def __str__(self):
        return f"{self.title}: {self.average_rating()}"


# Rating Model - the user input and passes into recipe to create the avg
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.recipe.title}: {self.rating}"


# Comment Model - Inspired by CodeInstitue
class Comment(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="comments"
    )
    name = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comments"
    )
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

templates/index.html
{% extends "base/base.html" %}
{% block head_title %}Home{% endblock %}
{% block content %}

<div class="container-fluid">
    <div class="container text-center my-3">
        <div class="row py-5">
            <div class="text-center recent-background mb-3">
                <h1>Recent Recipes</h1>
            </div>
            <!-- Recipe Django loops through all published recipes -->
            {% for recipe in recipes %}
            <div class="col-md-3">
                <div class="card md-3">
                    <a href="{% url 'recipe_detail' recipe.slug  %}" class="recipe-link">
                        <div class="card-body">
                            {% if "placeholder" in recipe.featured_image.url %}
                            <img class="img-card"
                                src="https://res.cloudinary.com/dnyfx3g7s/image/upload/v1694383398/seasonality_background.png"
                                alt="default recipe image">
                            {% else %}
                            <img class="img-card" src="{{ recipe.featured_image.url }}" alt="recipe image">
                            {% endif %}
                            <div class="image-flash">
                                <p class="author">Author: {{ recipe.author }}</p>
                            </div>
                        </div>
                        <h3 class="card-title">{{ recipe.title }}</h3>
                        <hr class="card-hr">
                        <p class="card-text text-muted-6">{{ recipe.created_on }}</p>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<!-- Pagination Controls -->
<nav aria-label="Page navigation">
{% if recipes.has_previous %}
    <div class="col-12">
            <a class="carousel-control-prev" href="?page={{ recipes.previous_page_number }}" role="button" data-slide="prev">
                <span class="fa-solid fa-circle-chevron-left fa-xl" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
    </div>
    {% endif %}
    {% if recipes.has_next %}
    <div class="col-12">
        <a class="carousel-control-next" href="?page={{ recipes.next_page_number }}" role="button" data-slide="next">
            <span class="fa-solid fa-circle-chevron-right fa-xl" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    {% endif %}
</nav>

<!-- Loop that goes through first three Diets in list, then displays 4 recipes on home page -->
{% for diet in diets|slice:":3" %}
<div class="container-fluid">
    <div class="container my-3">
        <div class="text-center diet-background">
            <h2 class="text-center">{{ diet.name }}</h2>
        </div>
        <div class="row pb-5 mt-2">
            {% for recipe in diet.recipe_set.all|slice:":4" %}
            {% if recipe.status %}
            <div class="col-md-3 d-flex flex-row text-center">
                <div class="card mx-auto">
                    <a href="{% url 'recipe_detail' recipe.slug  %}" class="recipe-link">
                        <div class="card-body">
                            {% if "placeholder" in recipe.featured_image.url %}
                            <img class="img-card"
                                src="https://res.cloudinary.com/dnyfx3g7s/image/upload/v1694383398/seasonality_background.png"
                                alt="bowl of berries next to rubarb and flowers">
                            {% else %}
                            <img class="card-img" src="{{ recipe.featured_image.url }}">
                            {% endif %}
                            <div class="image-flash">
                                <p class="author">Author: {{ recipe.author }}</p>
                            </div>
                        </div>
                        <h3 class="card-title">{{ recipe.title }}</h3>
                        <hr class="card-hr">
                        <p class="card-text text-muted-6">{{ recipe.created_on }}</p>
                    </a>
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}